version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: omniroute-gateway_web_1
      APP_PORT: 20128

  web:
    image: diegosouzapw/omniroute:latest
    restart: on-failure
    stop_grace_period: 40s
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
